Repository FerretDB/documentdb, pull requests merged in 2025-03, with the labels that each got.

#16 Define Docker build tags
  .github/workflows/ferretdb_packages.yml
  ferretdb_packaging/defineversion/docker_tags.go
  ferretdb_packaging/defineversion/docker_tags_test.go
  ferretdb_packaging/defineversion/main.go
  ferretdb_packaging/defineversion/main_test.go
Labels: packages

#25 Prepare Docker images builds
  .github/workflows/ferretdb_packages.yml
  ferretdb_packaging/10-preload.sh
  ferretdb_packaging/20-install.sql
  ferretdb_packaging/90-install-development.sql
  ferretdb_packaging/Dockerfile_build_deb_packages
  ferretdb_packaging/Makefile
  ferretdb_packaging/buildkitd.toml
  ferretdb_packaging/defineversion/main.go
  ferretdb_packaging/development.Dockerfile
  ferretdb_packaging/production.Dockerfile
Labels: packages, trust

#26 Minor tweaks
  .github/workflows/ferretdb_packages.yml
  ferretdb_packaging/Makefile
  ferretdb_packaging/defineversion/docker.go
  ferretdb_packaging/defineversion/docker_test.go
  ferretdb_packaging/defineversion/main.go
Labels: packages, trust

#27 Fix Docker images building
  .github/workflows/ferretdb_packages.yml
  ferretdb_packaging/Makefile
  ferretdb_packaging/development.Dockerfile
  ferretdb_packaging/production.Dockerfile
Labels: packages, trust

#28 Enable other registries
  ferretdb_packaging/defineversion/docker.go
  ferretdb_packaging/defineversion/main_test.go
Labels: packages, trust

#30 Add more Docker tags
  ferretdb_packaging/defineversion/debian.go
  ferretdb_packaging/defineversion/docker.go
  ferretdb_packaging/defineversion/main_test.go
Labels: packages, trust

#31 Adding minor statement to README (#86)
  README.md
Labels: not ready

#32 Remove `branch` from Debian package versions
  ferretdb_packaging/defineversion/debian.go
  ferretdb_packaging/defineversion/docker.go
  ferretdb_packaging/defineversion/docker_test.go
  ferretdb_packaging/defineversion/main.go
  ferretdb_packaging/defineversion/main_test.go
Labels: packages, trust

#37 Prepare v0.102.0-ferretdb-2.0.0 (GA) release
  CHANGELOG.md
  ferretdb_packaging/go.mod
Labels: packages, trust

#36 Check control file default version
  ferretdb_packaging/defineversion/main.go
  ferretdb_packaging/defineversion/main_test.go
Labels: packages, trust

#41 Fix handling of explicit `maxTimeMS` zero values
  pg_documentdb/src/commands/commands_common.c
Labels: packages, trust

#43 Fix `listDatabases` and related commands
  pg_documentdb/src/commands/db_stats.c
Labels: packages, trust
